function createfigure(x1, y1, x2, y2)
%CREATEFIGURE(X1,Y1,X2,Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
 
%  Auto-generated by MATLAB on 18-Nov-2004 14:16:43
 
%% Create figure
figure1 = figure;
 
%% Create axes
axes1 = axes('Parent',figure1);
title(axes1,'Forward Biased Diode Characteristics');
xlabel(axes1,'(Vd) Forward Biased Voltage across the Diode');
ylabel(axes1,'(Id) Forward Biased Current across the Diode');
grid(axes1,'on');
hold(axes1,'all');
 
%% Create plot
plot1 = plot(x1,y1,'LineWidth',2);
 
%% Create plot
plot2 = plot(...
  x2,y2,...
  'Color',[1 0 0],...
  'LineWidth',2);
 
